# Conversion to YAML from Properties formar report
spring:
  application:
    name: EJ2-b-Consumer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server:
  port: 8081
api:
  server:
    url: http://localhost:8080/api/v1
  base:
    url: http://localhost:8080/api/v1
logging:
  level:
    org:
      springframework:
        web: info
    com:
      practica: debug
